### PR TITLE
MIDIInputMap.outputs no longer a function in new chrome

### LINKED ISSUE #131: Error in plugin.webmidi.js. Outputs is not a function.
Don't work this code:
MIDI.loadPlugin({
        soundfontUrl: "./soundfont/",
        instrument: "acoustic_grand_piano",
        onprogress: function(state, progress) {
            console.log(state, progress);
        },
        onsuccess: function() {
  			play();
        }
    });
Error: plugin.webmidi.js:69 Uncaught (in promise) TypeError: object is not a function.
Error occurs in Chrome when enable flag web-midi-api.
Can you help me resolve this problem?

### PR DESCRIPTION
**Pull request by mscuthbert**
The newest version of Chrome makes `MIDIInputMap` (access/plugin) return an object, not a function when `.outputs` is called.  That object may have zero length, in which case the fallback to webaudio should be called. See https://code.google.com/p/chromium/issues/detail?id=341423 for details on the change. Fixes #131 .  My first MIDI.js pull request, so I'm not sure if the build/MIDI.js etc. were supposed to be included.

### CODE REVIEW

**Comment by anastasiyaShahova** [comment]
I need this feature too. Please, merge this pull request.

**Comment by mikejcorey** [comment]
+1. This issue is breaking my code.

**Comment by anastasiyaShahova** [comment]
@mscuthbert , Thank you for your pull request. I pulled into my fork and my code started to work. It seems that @mudcube is not engaged in this library.

**Comment by mattbgold** [comment]
Thanks @mscuthbert for fixing this!

**Comment by mudcube** [comment]
Thanks for the update @mscuthbert! Sorry for slow response.

**Pull request merged**
